/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.56
 * Generated at: 2020-10-02 05:38:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class todo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <!-- font-family: 'Montserrat', sans-serif; -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,500i,600,600i,700\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&subset=korean\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- css -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/common.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- js -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"js/common.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/work.css\">\r\n");
      out.write("    <script src=\"js/work.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <title>withWork</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("        <dl class=\"groupInfo headerInner\">\r\n");
      out.write("            <dt>GOOGLE</dt>\r\n");
      out.write("            <dd>\r\n");
      out.write("                <img src=\"img/user.png\" alt=\"\">\r\n");
      out.write("                <span>최은서</span>님, 안녕하세요.\r\n");
      out.write("            </dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("        <ul class=\"allInfo\">\r\n");
      out.write("            <li class=\"active\"><a href=\"todo.html\" class=\"todoIcon\">TO-DO</a></li>\r\n");
      out.write("            <li><a href=\"confirm.html\" class=\"confirmIcon\">CONFIRM</a></li>\r\n");
      out.write("            <li><a href=\"roadmap.html\" class=\"roadMapIcon\">ROADMAP</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <dl class=\"headerInner\">\r\n");
      out.write("            <dt>참여중인 프로젝트</dt>\r\n");
      out.write("            <dd class=\"projectSearch\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"프로젝트명을 입력해주세요.\">\r\n");
      out.write("                <input type=\"button\" value=\"\">\r\n");
      out.write("            </dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("        <ul class=\"projectList\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\" class=\"projectTit\">SAMSUNG 리뉴얼</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"notice.html\">TO-DO</a></li>\r\n");
      out.write("                    <li><a href=\"notice.html\">NOTICE</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"#\" class=\"projectTit\">LG 유지보수</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"notice.html\">TO-DO</a></li>\r\n");
      out.write("                    <li><a href=\"notice.html\">NOTICE</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </header>\r\n");
      out.write("    <section>\r\n");
      out.write("        <dl class=\"conTit department\" style=\"border-bottom: 0;\">\r\n");
      out.write("            <dt>\r\n");
      out.write("                TO-DO\r\n");
      out.write("                <a href=\"#\" class=\"workAddBtn\"><img src=\"img/todoAdd.png\" alt=\"\" width=\"35\"></a>\r\n");
      out.write("            </dt>\r\n");
      out.write("            <dd>오늘의 할 일을 확인해보세요.</dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("        <div class=\"todoTab\">\r\n");
      out.write("            <ul class=\"todoNav\">\r\n");
      out.write("                <li class=\"active\"><a href=\"#\">All</a></li>\r\n");
      out.write("                <li><a href=\"#\">DESIGN TEAM</a></li>\r\n");
      out.write("                <li class=\"project\"><a href=\"#\">SAMSUNG 리뉴얼</a></li>\r\n");
      out.write("                <li class=\"project\"><a href=\"#\">LG 유지보수</a></li>\r\n");
      out.write("                <li><a href=\"#\">그 외</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"todoCont\">\r\n");
      out.write("                <li class=\"active\">\r\n");
      out.write("                    <ul class=\"todoContList listItem\">\r\n");
      out.write("                        <li class=\"import\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <span class=\"todoContTxt\">11111111111111</span>\r\n");
      out.write("                                <span class=\"deadLine\">(3일 남았습니다.)</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"import\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <span class=\"todoContTxt\">222222222222222222222222222222222</span>\r\n");
      out.write("                                <span class=\"deadLine\">(1일 남았습니다.)</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <span class=\"todoContTxt\">333333333333333</span>\r\n");
      out.write("                                <span class=\"deadLine\">(7일 남았습니다.)</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <span class=\"todoContTxt\">4444444444444444</span>\r\n");
      out.write("                                <span class=\"deadLine\">(3일 남았습니다.)</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"import\">\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <span class=\"todoContTxt\">55555555555555</span>\r\n");
      out.write("                                <span class=\"deadLine\">(1일 남았습니다.)</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <span class=\"todoContTxt\">666</span>\r\n");
      out.write("                                <span class=\"deadLine\">(7일 남았습니다.)</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <ul class=\"todoContList listItem\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <span class=\"todoContTxt\">DESIGN TEAM 영역</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <ul class=\"todoContList listItem\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <span class=\"todoContTxt\">SAMSUNG 리뉴얼 영억</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <ul class=\"todoContList listItem\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <span class=\"todoContTxt\">LG 유지보수 영역</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <ul class=\"todoContList listItem\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"#\">\r\n");
      out.write("                                <span class=\"todoContTxt\">그 외 영역</span>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <dl class=\"conTit department bigMG\">\r\n");
      out.write("            <dt class=\"dtImg\">\r\n");
      out.write("                DESIGN TEAM\r\n");
      out.write("                <a href=\"#\" class=\"teamAddBtn\"><img src=\"img/teamAdd.png\" alt=\"\" width=\"35\"></a>\r\n");
      out.write("            </dt>\r\n");
      out.write("            <dd>팀원들의 업무를 확인해보세요.</dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("        <div class=\"departTodo smallMG\">\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dt>\r\n");
      out.write("                    <span class=\"memberName\">권은영 팀장</span>\r\n");
      out.write("                    <span class=\"todoType\">\r\n");
      out.write("                        <span class=\"bullet\">&bull;</span>\r\n");
      out.write("                        2\r\n");
      out.write("                        <span class=\"bullet\">&bull;</span>\r\n");
      out.write("                        4\r\n");
      out.write("                    </span>\r\n");
      out.write("                </dt>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <ul class=\"listItem\">\r\n");
      out.write("                        <li class=\"import\"><a href=\"#\">과제 컨펌</a></li>\r\n");
      out.write("                        <li class=\"import\"><a href=\"#\">넷플릭스 미팅</a></li>\r\n");
      out.write("                        <li><a href=\"#\">가진동 내조</a></li>\r\n");
      out.write("                        <li><a href=\"#\">CF역할놀이</a></li>\r\n");
      out.write("                        <li><a href=\"#\">가진동 내조</a></li>\r\n");
      out.write("                        <li><a href=\"#\">CF역할놀이</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dt>\r\n");
      out.write("                    <span class=\"memberName\">곽은진 과장</span>\r\n");
      out.write("                    <span class=\"todoType\">\r\n");
      out.write("                        <span class=\"bullet\">&bull;</span>\r\n");
      out.write("                        1\r\n");
      out.write("                        <span class=\"bullet\">&bull;</span>\r\n");
      out.write("                        1\r\n");
      out.write("                    </span>\r\n");
      out.write("                </dt>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <ul class=\"listItem\">\r\n");
      out.write("                        <li class=\"import\"><a href=\"#\">종이의집 시청</a></li>\r\n");
      out.write("                        <li><a href=\"#\">찜닭 먹기</a></li>\r\n");
      out.write("                    </ul>                   \r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dt>\r\n");
      out.write("                    <span class=\"memberName\">이민형 주임</span>\r\n");
      out.write("                    <span class=\"todoType\">\r\n");
      out.write("                        <span class=\"bullet\">&bull;</span>\r\n");
      out.write("                        3\r\n");
      out.write("                        <span class=\"bullet\">&bull;</span>\r\n");
      out.write("                        1\r\n");
      out.write("                    </span>\r\n");
      out.write("                </dt>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <ul class=\"listItem\">\r\n");
      out.write("                        <li class=\"import\"><a href=\"#\">포동이 놀아주기</a></li>\r\n");
      out.write("                        <li class=\"import\"><a href=\"#\">프리즌 브레이크 시청</a></li>\r\n");
      out.write("                        <li class=\"import\"><a href=\"#\">스크류바 사주기</a></li>\r\n");
      out.write("                        <li><a href=\"#\">마스크 벗고 얘기하기</a></li>\r\n");
      out.write("                    </ul>                    \r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("            <dl>\r\n");
      out.write("                <dt>\r\n");
      out.write("                    <span class=\"memberName\">이충진 사원</span>\r\n");
      out.write("                    <span class=\"todoType\">\r\n");
      out.write("                        <span class=\"bullet\">&bull;</span>\r\n");
      out.write("                        0\r\n");
      out.write("                        <span class=\"bullet\">&bull;</span>\r\n");
      out.write("                        1\r\n");
      out.write("                    </span>\r\n");
      out.write("                </dt>\r\n");
      out.write("                <dd>\r\n");
      out.write("                    <ul class=\"listItem\">\r\n");
      out.write("                        <li><a href=\"#\">DB 설계하기</a></li>\r\n");
      out.write("                    </ul>                    \r\n");
      out.write("                </dd>\r\n");
      out.write("            </dl>\r\n");
      out.write("        </div>        \r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- popup include -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <ul class=\"quickBar\">\r\n");
      out.write("            <li class=\"members\">\r\n");
      out.write("                <a href=\"#\"><img src=\"img/users.png\" alt=\"\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"chatBtn\">\r\n");
      out.write("                <a href=\"#\"><img src=\"img/chat.png\" alt=\"\"></a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <dl class=\"pop memberCont\">\r\n");
      out.write("        <dt>\r\n");
      out.write("            그룹멤버\r\n");
      out.write("            <a href=\"#\">X</a>\r\n");
      out.write("        </dt>\r\n");
      out.write("        <dd>\r\n");
      out.write("            <div class=\"memberTab\">\r\n");
      out.write("                <ul class=\"tabs\">\r\n");
      out.write("                    <li class=\"active\"><a href=\"#\">전체보기</a></li>\r\n");
      out.write("                    <li><a href=\"#\">멤버초대</a></li>\r\n");
      out.write("                    <li><a href=\"#\">멤버수정</a></li>\r\n");
      out.write("                    <li><a href=\"#\">멤버삭제</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 검색 영역 -->\r\n");
      out.write("            <div class=\"projectSearch search\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"이름, 아이디, 이메일 중 하나를 입력해주세요.\">\r\n");
      out.write("                <input type=\"button\" value=\"\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"tab_content\">\r\n");
      out.write("                <!-- 전체보기 영역 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <ul class=\"memberTeam\">\r\n");
      out.write("                        <li><a href=\"#\">> 디자인팀</a></li>\r\n");
      out.write("                        <li class=\"memberList\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><img src=\"img/usericon.png\"  alt=\"\">곽은진&nbsp&nbsp&nbsptest.com</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>  \r\n");
      out.write("                    <ul class=\"memberTeam\">\r\n");
      out.write("                        <li><a href=\"#\">> 마케팅팀</a></li>\r\n");
      out.write("                        <li class=\"memberList\">\r\n");
      out.write("                            <ul class=\"memberName\">\r\n");
      out.write("                                <li><img src=\"img/usericon.png\"  alt=\"\">최은서</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>  \r\n");
      out.write("                    <ul class=\"memberTeam\">\r\n");
      out.write("                        <li><a href=\"#\">> 기획팀</a></li>\r\n");
      out.write("                        <li class=\"memberList\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li><img src=\"img/usericon.png\"  alt=\"\">권은영</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 멤버검색 영역 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"table searchMember\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <colgroup>\r\n");
      out.write("                                <col width=\"10%\">\r\n");
      out.write("                                <col width=\"40%\"/>\r\n");
      out.write("                                <col width=\"17.5%\"/>\r\n");
      out.write("                                <col width=\"17.5%\"/>\r\n");
      out.write("                                <col width=\"15%\"/>\r\n");
      out.write("                            </colgroup>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th><img src=\"img/usericon.png\"  alt=\"\"></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <p>곽은진</p>\r\n");
      out.write("                                    <p class=\"emailTxt\">test@test.com</p>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <select class=\"sel\">\r\n");
      out.write("                                        <option>그룹선택</option>\r\n");
      out.write("                                        <option>마케팅팀</option>\r\n");
      out.write("                                        <option>디자인팀</option>\r\n");
      out.write("                                        <option>기획팀</option>\r\n");
      out.write("                                        <option>재무관리팀</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <select class=\"sel\">\r\n");
      out.write("                                        <option>권한선택</option>\r\n");
      out.write("                                        <option>관리자</option>\r\n");
      out.write("                                        <option>멤버</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>초대<!-- <input type=\"checkbox\"> --></td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 멤버수정 영역 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"table searchMember\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <colgroup>\r\n");
      out.write("                                <col width=\"10%\">\r\n");
      out.write("                                <col width=\"40%\"/>\r\n");
      out.write("                                <col width=\"17.5%\"/>\r\n");
      out.write("                                <col width=\"17.5%\"/>\r\n");
      out.write("                                <col width=\"15%\"/>\r\n");
      out.write("                            </colgroup>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th><img src=\"img/usericon.png\"  alt=\"\"></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <p>최은서</p>\r\n");
      out.write("                                    <p class=\"emailTxt\">test@test.com</p>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <select class=\"sel\">\r\n");
      out.write("                                        <option>그룹선택</option>\r\n");
      out.write("                                        <option>마케팅팀</option>\r\n");
      out.write("                                        <option>디자인팀</option>\r\n");
      out.write("                                        <option>기획팀</option>\r\n");
      out.write("                                        <option>재무관리팀</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <select class=\"sel\">\r\n");
      out.write("                                        <option>권한선택</option>\r\n");
      out.write("                                        <option>관리자</option>\r\n");
      out.write("                                        <option>멤버</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>수정</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 멤버삭제 영역 -->\r\n");
      out.write("                <div>\r\n");
      out.write("                    <div class=\"table searchMember\">\r\n");
      out.write("                        <table>\r\n");
      out.write("                            <colgroup>\r\n");
      out.write("                                <col width=\"10%\">\r\n");
      out.write("                                <col width=\"40%\"/>\r\n");
      out.write("                                <col width=\"17.5%\"/>\r\n");
      out.write("                                <col width=\"17.5%\"/>\r\n");
      out.write("                                <col width=\"15%\"/>\r\n");
      out.write("                            </colgroup>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th><img src=\"img/usericon.png\"  alt=\"\"></th>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <p>권은영</p>\r\n");
      out.write("                                    <p class=\"emailTxt\">test@test.com</p>\r\n");
      out.write("                                </td>\r\n");
      out.write("                                <td>마케팅팀</td>\r\n");
      out.write("                                <td>관리자</td>\r\n");
      out.write("                                <td>삭제</td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </dd>\r\n");
      out.write("    </dl>\r\n");
      out.write("    <div class=\"popupM msgPopup\">\r\n");
      out.write("        <dl>\r\n");
      out.write("            <dt>\r\n");
      out.write("                SAMSUNG 리뉴얼\r\n");
      out.write("                <a href=\"#\" class=\"popupOK\">X</a>\r\n");
      out.write("            </dt>\r\n");
      out.write("        </dl>\r\n");
      out.write("        <ul class=\"msgPopupC\">\r\n");
      out.write("            <li><a href=\"#\" class=\"chatMenu1\">멤버</a></li>\r\n");
      out.write("            <li><a href=\"#\" class=\"chatMenu2\">대화방</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div class=\"projectSearch searchMemberChat\">\r\n");
      out.write("            <input type=\"text\" placeholder=\"&nbsp&nbsp멤버를 검색하세요.\">\r\n");
      out.write("            <input type=\"button\" value=\"\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"msgPopupAll\">\r\n");
      out.write("            <div class=\"msgPopupA\">\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">권은영 팀장</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">카트 들어오세요</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">이충진 상무</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">이클립스 끊었습니다.</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">곽은진 과장</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">아 배고파 ㅠㅠㅠ</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">박실 대리</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">아니,, 그니까~~</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">이민형 사원</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">자리비움</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">원윤희 사원</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">다들 말 좀 걸어줘요~</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">유영준 인턴</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">소곤 소곤..</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">유영준 인턴</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">소곤 소곤..</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">유영준 인턴</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">소곤 소곤..</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">유영준 인턴</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">소곤 소곤..</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">유영준 인턴</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">소곤 소곤..</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"msgPopupB\">\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">권은영 팀장, 최은서 부사장, 곽은진 과장</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">카트중...</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">이충진 상무, 박실 대리</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">의왕 단톡방입니다.</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"profileImg\">\r\n");
      out.write("                    <dl>\r\n");
      out.write("                        <dt class=\"memPopup\">이민형 사원, 유영준 인턴</dt>\r\n");
      out.write("                        <dd class=\"onlineId\">인턴 정신교육중..</dd>\r\n");
      out.write("                    </dl>\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"popupP chatProfile\">\r\n");
      out.write("        <dl>\r\n");
      out.write("            <dt>\r\n");
      out.write("                프로필\r\n");
      out.write("                <a href=\"#\" class=\"popupOK1\">X</a>\r\n");
      out.write("            </dt>\r\n");
      out.write("            <dd>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <img src=\"img/profile.png\" alt=\"\" width=\"110px\">\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>권은영 팀장</li>\r\n");
      out.write("                    <li>카트 들어오세요</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <div class=\"btnBox set2\">\r\n");
      out.write("                    <a href=\"#\">1:1 채팅</a>\r\n");
      out.write("                    <a href=\"#\">채팅방 초대</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("    </div>     \r\n");
      out.write("    <div class=\"popup workPopup\">\r\n");
      out.write("        <dl>\r\n");
      out.write("            <dt>\r\n");
      out.write("                업무 상세보기\r\n");
      out.write("            </dt>\r\n");
      out.write("            <dd>\r\n");
      out.write("                <div class=\"table workDetail\">\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <colgroup>\r\n");
      out.write("                            <col width=\"15%\">\r\n");
      out.write("                            <col width=\"30%\">\r\n");
      out.write("                            <col width=\"15%\">\r\n");
      out.write("                            <col width=\"30%\">\r\n");
      out.write("                        </colgroup>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>업무</th>\r\n");
      out.write("                            <td colspan=\"3\">포동이 놀아주기</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>내용</th>\r\n");
      out.write("                            <td colspan=\"3\">포동이를 놀이방으로 데려가세요.</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>지시자</th>\r\n");
      out.write("                            <td>권은영 팀장<br>(DESIGN TEAM)</td>\r\n");
      out.write("                            <th>업무자</th>\r\n");
      out.write("                            <td>이민형 주임<br>(DESIGN TEAM)</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>기한</th>\r\n");
      out.write("                            <td colspan=\"3\">20200101 ~ 20200124</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>상태</th>\r\n");
      out.write("                            <td colspan=\"3\">진행 중</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>               \r\n");
      out.write("                <div class=\"btnBox\">\r\n");
      out.write("                    <a href=\"#\" class=\"popupOK\">확인</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("    </div>     \r\n");
      out.write("    <div class=\"popup workAddPopup\">\r\n");
      out.write("        <dl>\r\n");
      out.write("            <dt>\r\n");
      out.write("                업무 추가\r\n");
      out.write("                <a href=\"#\" class=\"popupOK\">X</a>\r\n");
      out.write("            </dt>\r\n");
      out.write("            <dd>\r\n");
      out.write("                <div class=\"table workDetail\">\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <colgroup>\r\n");
      out.write("                            <col width=\"15%\">\r\n");
      out.write("                            <col width=\"30%\">\r\n");
      out.write("                            <col width=\"15%\">\r\n");
      out.write("                            <col width=\"30%\">\r\n");
      out.write("                        </colgroup>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>업무</th>\r\n");
      out.write("                            <td colspan=\"3\"><input type=\"text\"></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>내용</th>\r\n");
      out.write("                            <td colspan=\"3\"><input type=\"text\"></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>지시자</th>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <select disabled>\r\n");
      out.write("                                    <option value=\"최은서(사원)\">최은서(사원)</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </td>\r\n");
      out.write("                            <th>업무자</th>\r\n");
      out.write("                            <td>\r\n");
      out.write("                                <select>\r\n");
      out.write("                                    <option value=\"최은서(사원)\">최은서(사원)</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>기한</th>\r\n");
      out.write("                            <td colspan=\"3\">\r\n");
      out.write("                                <input type=\"date\">\r\n");
      out.write("                                &nbsp;~&nbsp;\r\n");
      out.write("                                <input type=\"date\">\r\n");
      out.write("                            </td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>               \r\n");
      out.write("                <div class=\"btnBox\">\r\n");
      out.write("                    <a href=\"#\" class=\"popupOK\">확인</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </dd>\r\n");
      out.write("        </dl>\r\n");
      out.write("    </div>     \r\n");
      out.write("    <div class=\"darkBack\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
